name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Build alpine-cmake image
      run: docker build ./alpine-cmake -t tingoose/alpine-cmake
    
    - name: Docker Build alpine-cmake-doxygen image
      run: docker build ./alpine-cmake-doxygen -t tingoose/alpine-cmake-doxygen
    
    - name: Docker Build cuda-cmake image
      run: docker build ./cuda-cmake -t tingoose/cuda-cmake
