name: Build and publish all images in repo

on:
  push:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build-Push alpine-cmake
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          repository: proffarnsw/alpine-cmake
          dockerfile: alpine-cmake/Dockerfile
          tag_with_ref: true
      - name: Build-Push alpine-cmake-doxygen
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          repository: proffarnsw/alpine-cmake-doxygen
          dockerfile: alpine-cmake-doxygen/Dockerfile
          tag_with_ref: true
